# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_open = QtWidgets.QPushButton(ImageViewer)
        self.btn_open.setMinimumHeight(40)
        self.btn_open.setObjectName("btn_open")
        self.verticalLayout.addWidget(self.btn_open)
        self.label_image = QtWidgets.QLabel(ImageViewer)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setMinimumSize(QtCore.QSize(400, 400))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "Trình xem ảnh"))
        self.btn_open.setText(_translate("ImageViewer", "Mở ảnh"))
        self.label_image.setText(_translate("ImageViewer", "Ảnh sẽ hiển thị tại đây"))
