# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area = QtWidgets.QScrollArea(ImageViewer)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_content = QtWidgets.QWidget()
        self.scroll_content.setObjectName("scroll_content")
        self.scroll_layout = QtWidgets.QVBoxLayout(self.scroll_content)
        self.scroll_layout.setObjectName("scroll_layout")
        self.label_image = QtWidgets.QLabel(self.scroll_content)
        self.label_image.setMinimumSize(QtCore.QSize(400, 300))
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.scroll_layout.addWidget(self.label_image)
        self.scroll_area.setWidget(self.scroll_content)
        self.verticalLayout.addWidget(self.scroll_area)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btn_open = QtWidgets.QPushButton(ImageViewer)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_buttons.addWidget(self.btn_open)
        self.btn_zoom_in = QtWidgets.QPushButton(ImageViewer)
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.horizontalLayout_buttons.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(ImageViewer)
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.horizontalLayout_buttons.addWidget(self.btn_zoom_out)
        self.btn_rotate_left = QtWidgets.QPushButton(ImageViewer)
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.horizontalLayout_buttons.addWidget(self.btn_rotate_left)
        self.btn_rotate_right = QtWidgets.QPushButton(ImageViewer)
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.horizontalLayout_buttons.addWidget(self.btn_rotate_right)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "Trình xem ảnh nâng cao"))
        self.btn_open.setText(_translate("ImageViewer", "Mở ảnh"))
        self.btn_zoom_in.setText(_translate("ImageViewer", "Zoom +"))
        self.btn_zoom_out.setText(_translate("ImageViewer", "Zoom -"))
        self.btn_rotate_left.setText(_translate("ImageViewer", "Xoay trái"))
        self.btn_rotate_right.setText(_translate("ImageViewer", "Xoay phải"))
