# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area = QtWidgets.QScrollArea(ImageViewer)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_widget = QtWidgets.QWidget()
        self.scroll_area_widget.setObjectName("scroll_area_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scroll_area_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_image = QtWidgets.QLabel(self.scroll_area_widget)
        self.label_image.setMinimumSize(QtCore.QSize(400, 300))
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.verticalLayout_2.addWidget(self.label_image)
        self.scroll_area.setWidget(self.scroll_area_widget)
        self.verticalLayout.addWidget(self.scroll_area)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btn_open = QtWidgets.QPushButton(ImageViewer)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_buttons.addWidget(self.btn_open)
        self.btn_fit = QtWidgets.QPushButton(ImageViewer)
        self.btn_fit.setObjectName("btn_fit")
        self.horizontalLayout_buttons.addWidget(self.btn_fit)
        self.btn_one_to_one = QtWidgets.QPushButton(ImageViewer)
        self.btn_one_to_one.setObjectName("btn_one_to_one")
        self.horizontalLayout_buttons.addWidget(self.btn_one_to_one)
        self.btn_rotate_left = QtWidgets.QPushButton(ImageViewer)
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.horizontalLayout_buttons.addWidget(self.btn_rotate_left)
        self.btn_rotate_right = QtWidgets.QPushButton(ImageViewer)
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.horizontalLayout_buttons.addWidget(self.btn_rotate_right)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "Trình xem ảnh nâng cao"))
        self.btn_open.setText(_translate("ImageViewer", "Mở ảnh"))
        self.btn_fit.setText(_translate("ImageViewer", "Fit"))
        self.btn_one_to_one.setText(_translate("ImageViewer", "1:1"))
        self.btn_rotate_left.setText(_translate("ImageViewer", "Xoay trái"))
        self.btn_rotate_right.setText(_translate("ImageViewer", "Xoay phải"))
