# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(RegisterForm)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(RegisterForm)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(RegisterForm)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_email = QtWidgets.QLabel(RegisterForm)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(RegisterForm)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_email)
        self.label_password = QtWidgets.QLabel(RegisterForm)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(RegisterForm)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.label_confirm = QtWidgets.QLabel(RegisterForm)
        self.label_confirm.setObjectName("label_confirm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_confirm)
        self.lineEdit_confirm = QtWidgets.QLineEdit(RegisterForm)
        self.lineEdit_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirm.setObjectName("lineEdit_confirm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_confirm)
        self.btn_register = QtWidgets.QPushButton(RegisterForm)
        self.btn_register.setObjectName("btn_register")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_register)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Đăng ký"))
        self.label_name.setText(_translate("RegisterForm", "Họ và tên:"))
        self.label_email.setText(_translate("RegisterForm", "Email:"))
        self.label_password.setText(_translate("RegisterForm", "Mật khẩu:"))
        self.label_confirm.setText(_translate("RegisterForm", "Nhập lại mật khẩu:"))
        self.btn_register.setText(_translate("RegisterForm", "Đăng ký"))
